version: '3.8'

# Persistance volumes:
volumes:

  mongo-express:

# Network for connection with other servers:
networks:

  server-network:
    external: true

# Router servers architecture:
services:

  # Query router:
  mongos:
    image: mongo
    container_name: mongos
    restart: unless-stopped
    command: mongos --port 27017 --configdb config-replica-set/config-serverA:27019,config-serverB:27019,config-serverC:27019 --bind_ip 0.0.0.0 --keyFile /mongo.key
    networks:
      - server-network
    ports:
      - 20001:27017
    volumes:
    - ../mongo.key:/mongo.key
    - ./server-script:/server-script
    - ../../db/collection:/db/collection
    - ../../db/data:/db/data

  # MongoExpress GUI:
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    networks:
      - server-network
    ports:
      - 20002:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongos
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_BASICAUTH_USERNAME=basic
      - ME_CONFIG_BASICAUTH_PASSWORD=basic
    volumes:
      - mongo-express:/root/.mongo-express
